question_data = [{"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "The title of the 1969 film ;Krakatoa, East_of Java; is incorrect, as Krakatoa is in fact west of Java.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "There are no roads in\/out of Juneau, Alaska.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "The flag of South Africa features 7 colours.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "Gothenburg is the capital of Sweden.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "Antarctica is the largest desert in the world.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "Mongolia; was a part of the now non-existent U.S.S.R.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "Liechtenstein does not have an airport.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "There exists an island named &quot;Java&quot;.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "Vietnam is the only country in the world that starts with V. ",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                                                  {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                                   "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]}
                 ]
